INSERT INTO locations (iata_code, city_name, country, airport_name) VALUES
                                                                        ('ATL', 'Atlanta', 'United States', 'Hartsfield-Jackson Atlanta International Airport'),
                                                                        ('LAX', 'Los Angeles', 'United States', 'Los Angeles International Airport'),
                                                                        ('ORD', 'Chicago', 'United States', 'O’Hare International Airport'),
                                                                        ('DFW', 'Dallas', 'United States', 'Dallas/Fort Worth International Airport'),
                                                                        ('DEN', 'Denver', 'United States', 'Denver International Airport'),
                                                                        ('JFK', 'New York', 'United States', 'John F. Kennedy International Airport'),
                                                                        ('SFO', 'San Francisco', 'United States', 'San Francisco International Airport'),
                                                                        ('SEA', 'Seattle', 'United States', 'Seattle-Tacoma International Airport'),
                                                                        ('LAS', 'Las Vegas', 'United States', 'Harry Reid International Airport'),
                                                                        ('MCO', 'Orlando', 'United States', 'Orlando International Airport'),
                                                                        ('CLT', 'Charlotte', 'United States', 'Charlotte Douglas International Airport'),
                                                                        ('PHX', 'Phoenix', 'United States', 'Phoenix Sky Harbor International Airport'),
                                                                        ('IAH', 'Houston', 'United States', 'George Bush Intercontinental Airport'),
                                                                        ('MIA', 'Miami', 'United States', 'Miami International Airport'),
                                                                        ('BOS', 'Boston', 'United States', 'Logan International Airport'),
                                                                        ('MSP', 'Minneapolis', 'United States', 'Minneapolis-Saint Paul International Airport'),
                                                                        ('DTW', 'Detroit', 'United States', 'Detroit Metropolitan Airport'),
                                                                        ('PHL', 'Philadelphia', 'United States', 'Philadelphia International Airport'),
                                                                        ('LGA', 'New York', 'United States', 'LaGuardia Airport'),
                                                                        ('BWI', 'Baltimore', 'United States', 'Baltimore/Washington International Thurgood Marshall Airport'),
                                                                        ('SLC', 'Salt Lake City', 'United States', 'Salt Lake City International Airport'),
                                                                        ('DCA', 'Washington', 'United States', 'Ronald Reagan Washington National Airport'),
                                                                        ('SAN', 'San Diego', 'United States', 'San Diego International Airport'),
                                                                        ('TPA', 'Tampa', 'United States', 'Tampa International Airport'),
                                                                        ('HNL', 'Honolulu', 'United States', 'Daniel K. Inouye International Airport'),
                                                                        ('PDX', 'Portland', 'United States', 'Portland International Airport'),
                                                                        ('STL', 'St. Louis', 'United States', 'St. Louis Lambert International Airport'),
                                                                        ('BNA', 'Nashville', 'United States', 'Nashville International Airport'),
                                                                        ('AUS', 'Austin', 'United States', 'Austin-Bergstrom International Airport'),
                                                                        ('DAL', 'Dallas', 'United States', 'Dallas Love Field'),
                                                                        ('HOU', 'Houston', 'United States', 'William P. Hobby Airport'),
                                                                        ('MKE', 'Milwaukee', 'United States', 'General Mitchell International Airport'),
                                                                        ('RDU', 'Raleigh', 'United States', 'Raleigh-Durham International Airport'),
                                                                        ('SMF', 'Sacramento', 'United States', 'Sacramento International Airport'),
                                                                        ('IND', 'Indianapolis', 'United States', 'Indianapolis International Airport'),
                                                                        ('CMH', 'Columbus', 'United States', 'John Glenn Columbus International Airport'),
                                                                        ('PIT', 'Pittsburgh', 'United States', 'Pittsburgh International Airport'),
                                                                        ('MSY', 'New Orleans', 'United States', 'Louis Armstrong New Orleans International Airport'),
                                                                        ('SJC', 'San Jose', 'United States', 'Norman Y. Mineta San Jose International Airport'),
                                                                        ('CVG', 'Cincinnati', 'United States', 'Cincinnati/Northern Kentucky International Airport'),
                                                                        ('JAX', 'Jacksonville', 'United States', 'Jacksonville International Airport'),
                                                                        ('ANC', 'Anchorage', 'United States', 'Ted Stevens Anchorage International Airport'),
                                                                        ('OMA', 'Omaha', 'United States', 'Eppley Airfield'),
                                                                        ('MEM', 'Memphis', 'United States', 'Memphis International Airport'),
                                                                        ('BUR', 'Burbank', 'United States', 'Hollywood Burbank Airport'),
                                                                        ('SNA', 'Santa Ana', 'United States', 'John Wayne Airport'),
                                                                        ('PBI', 'West Palm Beach', 'United States', 'Palm Beach International Airport'),
                                                                        ('RSW', 'Fort Myers', 'United States', 'Southwest Florida International Airport'),
                                                                        ('OKC', 'Oklahoma City', 'United States', 'Will Rogers World Airport');
-- need to fix image urls
INSERT INTO flights (
    airline_name, airline_logo_url, flight_number, departure_airport, arrival_airport,
    departure_terminal, arrival_terminal, departure_gate, arrival_gate, departure_time,
    arrival_time, flight_duration, ticket_price
) VALUES
      ('Delta Airlines', 'https://example.com/delta.png', 'DL245', 'JFK', 'LAX', '4', '6', 'B12', 'C34', '2025-04-10 08:00:00', '2025-04-10 11:30:00', '06:30:00', 320.00),
      ('American Airlines', 'https://example.com/aa.png', 'AA789', 'ORD', 'MIA', '2', 'D', 'A5', 'D12', '2025-04-12 14:00:00', '2025-04-12 18:00:00', '04:00:00', 280.00),
      ('United Airlines', 'https://example.com/ua.png', 'UA102', 'SFO', 'SEA', '3', 'B', 'C7', 'B4', '2025-04-15 09:30:00', '2025-04-15 11:30:00', '02:00:00', 150.00),
      ('Southwest Airlines', 'https://example.com/sw.png', 'SW555', 'DEN', 'LAS', '1', 'E', 'D3', 'A20', '2025-04-18 12:45:00', '2025-04-18 14:15:00', '01:30:00', 130.00),
      ('JetBlue Airways', 'https://example.com/jb.png', 'B6201', 'BOS', 'ATL', 'C', 'F', 'B8', 'C22', '2025-04-20 07:15:00', '2025-04-20 10:15:00', '03:00:00', 210.00),
      ('Alaska Airlines', 'https://example.com/ak.png', 'AS330', 'SEA', 'SFO', 'N', '3', 'A10', 'C14', '2025-04-22 15:00:00', '2025-04-22 17:15:00', '02:15:00', 175.00),
      ('Spirit Airlines', 'https://example.com/spirit.png', 'NK905', 'DFW', 'ORD', 'E', 'H', 'B2', 'F20', '2025-04-25 06:30:00', '2025-04-25 08:45:00', '02:15:00', 95.00),
      ('Frontier Airlines', 'https://example.com/frontier.png', 'F9123', 'PHX', 'DEN', 'D', 'A', 'C15', 'B12', '2025-04-27 10:20:00', '2025-04-27 12:45:00', '01:25:00', 110.00),
      ('Hawaiian Airlines', 'https://example.com/ha.png', 'HA456', 'LAX', 'HNL', '5', 'G', 'D18', 'E22', '2025-04-30 09:00:00', '2025-04-30 12:30:00', '05:30:00', 400.00),
      ('British Airways', 'https://example.com/ba.png', 'BA212', 'BOS', 'LHR', 'E', '5', 'A4', 'C16', '2025-05-02 18:00:00', '2025-05-03 06:30:00', '07:30:00', 750.00);
