INSERT INTO locations (iata_code, city_name, country, airport_name) VALUES
                                                                        ('IAH', 'Houston', 'United States', 'George Bush Intercontinental Airport'),
                                                                        ('DAL', 'Dallas', 'United States', 'Dallas Love Field'),
                                                                        ('DCA', 'Washington', 'United States', 'Ronald Reagan Washington National Airport'),
                                                                        ('BNA', 'Nashville', 'United States', 'Nashville International Airport'),
                                                                        ('MCO', 'Orlando', 'United States', 'Orlando International Airport'),
                                                                        ('CMH', 'Columbus', 'United States', 'John Glenn Columbus International Airport'),
                                                                        ('TPA', 'Tampa', 'United States', 'Tampa International Airport'),
                                                                        ('FLL', 'Fort Lauderdale', 'United States', 'Fort Lauderdale-Hollywood International Airport'),
                                                                        ('BWI', 'Baltimore', 'United States', 'Baltimore/Washington International Thurgood Marshall Airport'),
                                                                        ('MDW', 'Chicago', 'United States', 'Chicago Midway International Airport'),
                                                                        ('DTW', 'Detroit', 'United States', 'Detroit Metropolitan Airport'),
                                                                        ('DEN', 'Denver', 'United States', 'Denver International Airport'),
                                                                        ('MCI', 'Kansas City', 'United States', 'Kansas City International Airport'),
                                                                        ('TUL', 'Tulsa', 'United States', 'Tulsa International Airport'),
                                                                        ('PHX', 'Phoenix', 'United States', 'Phoenix Sky Harbor International Airport'),
                                                                        ('LGB', 'Long Beach', 'United States', 'Long Beach Airport'),
                                                                        ('HOU', 'Houston', 'United States', 'William P. Hobby Airport'),
                                                                        ('LBB', 'Lubbock', 'United States', 'Lubbock Preston Smith International Airport'),
                                                                        ('MSY', 'New Orleans', 'United States', 'Louis Armstrong New Orleans International Airport'),
                                                                        ('AUS', 'Austin', 'United States', 'Austin-Bergstrom International Airport'),
                                                                        ('SJD', 'San Jose del Cabo', 'Mexico', 'Los Cabos International Airport'),
                                                                        ('BOS', 'Boston', 'United States', 'Logan International Airport'),
                                                                        ('HRL', 'Harlingen', 'United States', 'Valley International Airport'),
                                                                        ('LAS', 'Las Vegas', 'United States', 'Harry Reid International Airport'),
                                                                        ('SBA', 'Santa Barbara', 'United States', 'Santa Barbara Municipal Airport'),
                                                                        ('COS', 'Colorado Springs', 'United States', 'Colorado Springs Airport'),
                                                                        ('LIT', 'Little Rock', 'United States', 'Bill and Hillary Clinton National Airport'),
                                                                        ('PIT', 'Pittsburgh', 'United States', 'Pittsburgh International Airport'),
                                                                        ('SAT', 'San Antonio', 'United States', 'San Antonio International Airport'),
                                                                        ('ABQ', 'Albuquerque', 'United States', 'Albuquerque International Sunport'),
                                                                        ('BHM', 'Birmingham', 'United States', 'Birmingham-Shuttlesworth International Airport'),
                                                                        ('LAX', 'Los Angeles', 'United States', 'Los Angeles International Airport'),
                                                                        ('BUR', 'Burbank', 'United States', 'Hollywood Burbank Airport'),
                                                                        ('MDT', 'Harrisburg', 'United States', 'Harrisburg International Airport'),
                                                                        ('RSW', 'Fort Myers', 'United States', 'Southwest Florida International Airport'),
                                                                        ('IND', 'Indianapolis', 'United States', 'Indianapolis International Airport'),
                                                                        ('ELP', 'El Paso', 'United States', 'El Paso International Airport'),
                                                                        ('SNA', 'Santa Ana', 'United States', 'John Wayne Airport'),
                                                                        ('MYR', 'Myrtle Beach', 'United States', 'Myrtle Beach International Airport'),
                                                                        ('BUF', 'Buffalo', 'United States', 'Buffalo Niagara International Airport'),
                                                                        ('OKC', 'Oklahoma City', 'United States', 'Will Rogers World Airport'),
                                                                        ('PHL', 'Philadelphia', 'United States', 'Philadelphia International Airport'),
                                                                        ('STL', 'St. Louis', 'United States', 'St. Louis Lambert International Airport'),
                                                                        ('ATL', 'Atlanta', 'United States', 'Hartsfield-Jackson Atlanta International Airport'),
                                                                        ('GTR', 'Golden Triangle', 'United States', 'Golden Triangle Regional Airport'),
                                                                        ('SJC', 'San Jose', 'United States', 'Norman Y. Mineta San Jose International Airport'),
                                                                        ('OAK', 'Oakland', 'United States', 'Oakland International Airport'),
                                                                        ('PSP', 'Palm Springs', 'United States', 'Palm Springs International Airport'),
                                                                        ('SRQ', 'Sarasota', 'United States', 'Sarasota-Bradenton International Airport'),
                                                                        ('JAX', 'Jacksonville', 'United States', 'Jacksonville International Airport'),
                                                                        ('PWM', 'Portland', 'United States', 'Portland International Jetport'),
                                                                        ('MIA', 'Miami', 'United States', 'Miami International Airport'),
                                                                        ('BDL', 'Windsor Locks', 'United States', 'Bradley International Airport'),
                                                                        ('CLT', 'Charlotte', 'United States', 'Charlotte Douglas International Airport'),
                                                                        ('GCM', 'George Town', 'Cayman Islands', 'Owen Roberts International Airport'),
                                                                        ('PLS', 'Providenciales', 'Turks and Caicos', 'Providenciales International Airport'),
                                                                        ('RIC', 'Richmond', 'United States', 'Richmond International Airport'),
                                                                        ('CHS', 'Charleston', 'United States', 'Charleston International Airport'),
                                                                        ('ORD', 'Chicago', 'United States', 'O’Hare International Airport'),
                                                                        ('GEG', 'Spokane', 'United States', 'Spokane International Airport'),
                                                                        ('AUA', 'Oranjestad', 'Aruba', 'Queen Beatrix International Airport'),
                                                                        ('HDN', 'Hayden', 'United States', 'Yampa Valley Airport'),
                                                                        ('MEM', 'Memphis', 'United States', 'Memphis International Airport'),
                                                                        ('MAF', 'Midland', 'United States', 'Midland International Air and Space Port'),
                                                                        ('CRP', 'Corpus Christi', 'United States', 'Corpus Christi International Airport'),
                                                                        ('SAN', 'San Diego', 'United States', 'San Diego International Airport'),
                                                                        ('SMF', 'Sacramento', 'United States', 'Sacramento International Airport'),
                                                                        ('ROC', 'Rochester', 'United States', 'Greater Rochester International Airport'),
                                                                        ('LGA', 'New York', 'United States', 'LaGuardia Airport'),
                                                                        ('ONT', 'Ontario', 'United States', 'Ontario International Airport'),
                                                                        ('PVR', 'Puerto Vallarta', 'Mexico', 'Licenciado Gustavo Díaz Ordaz International Airport'),
                                                                        ('PDX', 'Portland', 'United States', 'Portland International Airport'),
                                                                        ('SEA', 'Seattle', 'United States', 'Seattle-Tacoma International Airport'),
                                                                        ('PNS', 'Pensacola', 'United States', 'Pensacola International Airport'),
                                                                        ('RDU', 'Raleigh-Durham', 'United States', 'Raleigh-Durham International Airport'),
                                                                        ('SFO', 'San Francisco', 'United States', 'San Francisco International Airport'),
                                                                        ('RNO', 'Reno', 'United States', 'Reno-Tahoe International Airport'),
                                                                        ('OMA', 'Omaha', 'United States', 'Eppley Airfield'),
                                                                        ('ISP', 'Islip', 'United States', 'Long Island MacArthur Airport'),
                                                                        ('SYR', 'Syracuse', 'United States', 'Syracuse Hancock International Airport'),
                                                                        ('MTJ', 'Montrose', 'United States', 'Montrose Regional Airport'),
                                                                        ('ECP', 'Panama City', 'United States', 'Northwest Florida Beaches International Airport'),
                                                                        ('PBI', 'West Palm Beach', 'United States', 'Palm Beach International Airport'),
                                                                        ('GRR', 'Grand Rapids', 'United States', 'Gerald R. Ford International Airport'),
                                                                        ('SAV', 'Savannah', 'United States', 'Savannah/Hilton Head International Airport'),
                                                                        ('IAD', 'Washington', 'United States', 'Washington Dulles International Airport'),
                                                                        ('TUS', 'Tucson', 'United States', 'Tucson International Airport'),
                                                                        ('SLC', 'Salt Lake City', 'United States', 'Salt Lake City International Airport'),
                                                                        ('ALB', 'Albany', 'United States', 'Albany International Airport'),
                                                                        ('CLE', 'Cleveland', 'United States', 'Cleveland Hopkins International Airport');

INSERT INTO flights (
    airline_name, airline_logo_url, flight_number, departure_airport, arrival_airport,
    departure_terminal, arrival_terminal, departure_gate, arrival_gate, departure_time,
    arrival_time, flight_duration, ticket_price
) VALUES
      ('Delta Airlines', 'https://example.com/delta.png', 'DL245', 'JFK', 'LAX', '4', '6', 'B12', 'C34', '2025-04-10 08:00:00', '2025-04-10 11:30:00', '06:30:00', 320.00),
      ('American Airlines', 'https://example.com/aa.png', 'AA789', 'ORD', 'MIA', '2', 'D', 'A5', 'D12', '2025-04-12 14:00:00', '2025-04-12 18:00:00', '04:00:00', 280.00),
      ('United Airlines', 'https://example.com/ua.png', 'UA102', 'SFO', 'SEA', '3', 'B', 'C7', 'B4', '2025-04-15 09:30:00', '2025-04-15 11:30:00', '02:00:00', 150.00),
      ('Southwest Airlines', 'https://example.com/sw.png', 'SW555', 'DEN', 'LAS', '1', 'E', 'D3', 'A20', '2025-04-18 12:45:00', '2025-04-18 14:15:00', '01:30:00', 130.00),
      ('JetBlue Airways', 'https://example.com/jb.png', 'B6201', 'BOS', 'ATL', 'C', 'F', 'B8', 'C22', '2025-04-20 07:15:00', '2025-04-20 10:15:00', '03:00:00', 210.00),
      ('Alaska Airlines', 'https://example.com/ak.png', 'AS330', 'SEA', 'SFO', 'N', '3', 'A10', 'C14', '2025-04-22 15:00:00', '2025-04-22 17:15:00', '02:15:00', 175.00),
      ('Spirit Airlines', 'https://example.com/spirit.png', 'NK905', 'DFW', 'ORD', 'E', 'H', 'B2', 'F20', '2025-04-25 06:30:00', '2025-04-25 08:45:00', '02:15:00', 95.00),
      ('Frontier Airlines', 'https://example.com/frontier.png', 'F9123', 'PHX', 'DEN', 'D', 'A', 'C15', 'B12', '2025-04-27 10:20:00', '2025-04-27 12:45:00', '01:25:00', 110.00),
      ('Hawaiian Airlines', 'https://example.com/ha.png', 'HA456', 'LAX', 'HNL', '5', 'G', 'D18', 'E22', '2025-04-30 09:00:00', '2025-04-30 12:30:00', '05:30:00', 400.00),
      ('British Airways', 'https://example.com/ba.png', 'BA212', 'BOS', 'LHR', 'E', '5', 'A4', 'C16', '2025-05-02 18:00:00', '2025-05-03 06:30:00', '07:30:00', 750.00);
